import Head from "next/head";
// import Image from "next/image";
import Link from "next/link";
import Form from "../components/Form";

export default function Home() {
  return (
    <div>
      <Head>
        <title>React Hook Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex justify-between items-center bg-gray-900 text-white text-lg font-mono font-semibold tracking-wider py-4 px-8">
        <Link href="/">
          <h1 className="cursor-pointer">LOGO</h1>
        </Link>
        <ul className="flex space-x-3">
          <Link href="/">
            <a className="cursor-pointer hover:text-gray-500">Utama</a>
          </Link>
          <Link href="/Daftar-Pelatih">
            <a className="cursor-pointer hover:text-gray-500">Pelatih</a>
          </Link>
          <Link href="/kami">
            <a className="cursor-pointer hover:text-gray-500">Kami</a>
          </Link>
        </ul>
      </nav>
      <main>
        <Form />
      </main>
    </div>
  );
}
